# Nom du workflow
name: Continuous Integration

# Événement déclenchant le workflow (ici, chaque fois qu'un push est effectué sur la branche "main")
on:
  push:
    branches:
      - '*' # Toutes les branches

# Environnement de travail (dans ce cas, une machine virtuelle sous Ubuntu 20.04)
jobs:
  build:
    runs-on: ubuntu-20.04

    # Étapes à effectuer pour le job "build"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      # Installe Gradle sur la machine virtuelle
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '7.3.3'

      # Exécute les tâches Gradle pour chaque projet
      - name: Build projects
        run: |
          cd Rewards
          ./gradlew clean
          ./gradlew build
          cd ..
          cd GpsUtil
          ./gradlew clean
          ./gradlew build
          cd ..
          cd TripPricer
          ./gradlew clean
          ./gradlew build
          cd ..
  deploy_build:
      needs: build
      runs-on: ubuntu-20.04
      steps:
        - name: Checkout repository
          uses: actions/checkout@v3
        - uses: actions/setup-java@v3
          with:
            distribution: temurin
            java-version: 11

        # Installe Gradle sur la machine virtuelle
        - name: Setup Gradle
          uses: gradle/gradle-build-action@v2
          with:
            gradle-version: '7.3.3'

    # Construit l'image Docker pour le projet GpsUtil
        - name: Build projects
          run: |
            cd Rewards
            ./gradlew clean
            ./gradlew build
            cd ..
            cd GpsUtil
            ./gradlew clean
            ./gradlew build
            cd ..
            cd TripPricer
            ./gradlew clean
            ./gradlew build
            cd ..

    # Lance le conteneur Docker pour le projet GpsUtil
        - name: Deploy GpsUtil
          run: |
            java -jar Rewards/build/libs/rewards-1.0.0.jar &
            java -jar GpsUtil/build/libs/gpsUtil-1.0.0.jar &
            java -jar TripPricer/build/libs/tripPricer-1.0.0.jar &
            sleep 30
        - name: Build TourGuide
          run : |
            cd TourGuide
            chmod +x gradlew
            ./gradlew build
